#--- Variables --------------------------------------------------------------------------------------------
PROJECT_NAME         = Brownie
PROJECT_VERSION      = 1.0.0
PROJECT_DESCRIPTION  = Graphical user interface for simulating random walks
PROJECT_AUTHORS      = Nicolas Lermé
PROJECT_LICENSE      = LGPL-v3
PROJECT_LAST_RELEASE = `date`
